### ISSUE TITLE
Error when running nif_finder.py KeyError: 'EXONS|__|count'

### ISSUE THREAD

**Issue by urwahnawaz** [jolespin/nif_finder#1]
Hi,

When running then nif_finder.py script, I'm getting the following error:  
```
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'EXONS|__|count'

```

I'm running this on the Mus_musculus.GRCm39.107.gtf.gz build after constructing the premrna.fa file and I'm using the corresponding cds file. Please note I set up the env for dependencies as provided on the README.md

**Comment by jolespin** [comment]
I haven't touched this program in quite a bit but I can try to help you out. Can you link me out to all the files you're using to make it easier?

**Comment by urwahnawaz** [comment]
That's all good. Yep, that'll be amazing! here they are

*  CDS
```
http://ftp.ensembl.org/pub/release-107/fasta/mus_musculus/cds/Mus_musculus.GRCm39.cds.all.fa.gz
```

* Genome assembly 

```
http://ftp.ensembl.org/pub/release-107/fasta/mus_musculus/dna/Mus_musculus.GRCm39.dna.primary_assembly.fa.gz
```

* GTF 

```
http://ftp.ensembl.org/pub/release-107/gtf/mus_musculus/Mus_musculus.GRCm39.107.gtf.gz
```

I actually wanted to know, in the results for the genome 39 build for mouse, where are only ~58,000 transcripts annotated? I wanted to rerun the program just to see if I was able to get NIF for all transcripts, but happy to reuse exisiting results if there was an actual reason for the missing data? 

Thank you!

**Comment by jolespin** [comment]
The reason for the missing transcripts in the resulting file is because some of the transcripts don't meet the criteria.  For example, if they don't have both a 5UTR and 3UTR then they won't be considered.  There's a log file that describes why each transcript was dismissed.

**Comment by jolespin** [comment]
Looking into this now. 

Here's my run: 

```bash
(nif-finder_env) [jespinoz@exp-15-01 Mus_musculus.GRCm39]$ python ../nif_finder/Scripts/get_premrna_sequences_from_gtf.py -a Mus_musculus.GRCm39.dna.primary_assembly.fa.gz -g Mus_musculus.GRCm39.107.gtf.gz > Mus_musculus.GRCm39.premRNA.fa
Reading: Mus_musculus.GRCm39.dna.primary_assembly.fa.gz: 61 sequence [00:26,  2.32 sequence/s]
Reading: Mus_musculus.GRCm39.107.gtf.gz: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1902020/1902020 [00:05<00:00, 369617.04 line/s]
Merging exon sequences: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 149478/149478 [00:17<00:00, 8660.39 transcript/s]
Writing pre-mRNA sequences: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 149478/149478 [00:02<00:00, 53074.34 sequence/s]
(nif-finder_env) [jespinoz@exp-15-01 Mus_musculus.GRCm39]$ ls -lh Mus_musculus.GRCm39.premRNA.fa
-rw-r--r-- 1 jespinoz jcl110 4.0G Sep 22 11:37 Mus_musculus.GRCm39.premRNA.fa
```

Here's the error I got: 

```
(nif-finder_env) [jespinoz@exp-15-01 Mus_musculus.GRCm39]$ python ../nif_finder/nif_finder.py -p Mus_musculus.GRCm39.premRNA.fa -c Mus_musculus.GRCm39.cds.all.fa.gz -o nif_output
Checking if directory exists, make one if not...
================================
 NIF Finder
================================
Mus_musculus
pre-mRNA:	Mus_musculus.GRCm39.premRNA.fa
CDS:	Mus_musculus.GRCm39.cds.all.fa.gz
Path:	nif_output
================
 Parameters
================
kozak_type: 	1
tol_min_codons: 	10
tol_dej: 	55
tol_long3utr	1200
tol_window	10
================
 Summary
================
Reading pre-mRNA. .. ... ..... .......: 149478it [00:06, 23716.70it/s]
Analyzing CDS. .. ... ..... .......: 67152it [00:01, 48927.24it/s]
Quality control. .. ... ..... ........: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 216630/216630 [00:00<00:00, 766272.38it/s]
Computing NIFs. .. ... ..... ........: 0it [00:00, ?it/s]
Writing files. .. ... ..... ........
Traceback (most recent call last):
  File "/expanse/projects/jcl110/anaconda3/envs/nif-finder_env/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3800, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'EXONS|__|count'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/expanse/projects/jcl110/NIF/Mus_musculus.GRCm39/../nif_finder/nif_finder.py", line 544, in <module>
    main()
  File "/expanse/projects/jcl110/NIF/Mus_musculus.GRCm39/../nif_finder/nif_finder.py", line 516, in main
    df_attrs["EXONS|__|count"] = df_attrs["EXONS|__|count"].astype(int)
  File "/expanse/projects/jcl110/anaconda3/envs/nif-finder_env/lib/python3.10/site-packages/pandas/core/frame.py", line 3805, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/expanse/projects/jcl110/anaconda3/envs/nif-finder_env/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    raise KeyError(key) from err
KeyError: 'EXONS|__|count'
```

The error is because the identifiers in the premRNA don't overlap with identifiers in the CDS file.  The CDS file has transcript versions appended (e.g., `ENSMUST00000178537.2` vs `ENSMUST00000178537`).

There's two solutions here: 1) Remove the transcript version from the CDS sequences or 2) add functionality to append the version to the premRNA. 

I'm looking at the code right now and I thought I accounted for this but apparently it's not working as expected.  I just fixed it now. 

```
(nif-finder_env) [jespinoz@exp-15-03 Mus_musculus.GRCm39]$ python ../nif_finder/nif_finder.py -p Mus_musculus.GRCm39.premRNA.fa -c Mus_musculus.GRCm39.cds.all.fa.gz -o nif_output
Checking if directory exists, make one if not...
================================
 NIF Finder
================================
Mus_musculus
pre-mRNA:	Mus_musculus.GRCm39.premRNA.fa
CDS:	Mus_musculus.GRCm39.cds.all.fa.gz
Path:	nif_output
================
 Parameters
================
kozak_type: 	1
tol_min_codons: 	10
tol_dej: 	55
tol_long3utr	1200
tol_window	10
================
 Summary
================
Reading pre-mRNA. .. ... ..... .......: 149478it [00:06, 23344.53it/s]
Analyzing CDS. .. ... ..... .......: 67152it [03:52, 288.81it/s]
Quality control. .. ... ..... ........: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 149478/149478 [00:00<00:00, 882765.82it/s]
Computing NIFs. .. ... ..... ........: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 59191/59191 [01:22<00:00, 715.79it/s]
Writing files. .. ... ..... ........
Transcripts Processed:	59191
Transcripts Dropped:	90287
uORFs:	19118
dEJs:	6068
Long 3'UTRs:	16295
Runtime: 331.9517641067505 seconds
```

Here's the output files:
[nif_output.zip](https://github.com/jolespin/nif_finder/files/9628803/nif_output.zip)
